esphome:
  name: catfeeder
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "[Insert SSID Here]"
  password: "[Insert password Here]"
# Use manual_ip if you want a static ip for better reliability, otherwise just use ssid and password
  manual_ip:
    static_ip: 
    gateway: 
    subnet: 

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Catfeeder Fallback Hotspot"
    password: "[Insert password Here]"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "[Insert password Here]"
  services:
    - service: control_servo
      variables:
        level: float
      then:
        - servo.write:
            id: catfeeder_tilt
            level: !lambda 'return level / 100.0;'
ota:
  password: ""
output:
  - platform: esp8266_pwm
    id: 'catfeeder'
    frequency: 50Hz
    pin: D1
    
servo:
  - output: 'catfeeder'
    id: catfeeder_tilt

sensor:
  - platform: dht
    pin: D6
    model: DHT11
    temperature:
      name: "CatFeeder Temperature"
    humidity:
      name: "CatFeeder Humidity"
    update_interval: 300s
  - platform: wifi_signal
    name: "CatFeeder RSSI"
    update_interval: 300s
  - platform: uptime
    name: "CatFeeder Uptime"
  - platform: ultrasonic
    trigger_pin: D8
    echo_pin: D7
    name: "Cat Food Remaining"
    update_interval: 60s
binary_sensor:
  - platform: gpio
    pin: D3
    name: "Cat Motion"
    device_class: motion
switch:
  - platform: restart
    name: "Restart CatFeeder"
